using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Progra1.Models
{
    public class SQLQuerys
    {
        /*QUERYS */
        public const string UPDATEPRODUCTO = "UPDATE PRODUCTO SET Nombre = @nom, Descripcion = @desc, PrecioCompra = @precioCompra, Impuesto = @impuesto WHERE CodigoBarras = @cod";
        public const string SELECTTRABAJADOR_CED = "SELECT * FROM TRABAJADOR WHERE CedulaPersona = @ced AND Estado = 0";
        public const string SELECTUSUARIO_USER_PASS = "SELECT* FROM USUARIO WHERE Usuario= @user AND Contrasena= @pw;";
        public const string SELECTROLID_CEDULATRAB = "SELECT ROLTRABAJADOR.IDRol, TRABAJA_EN.IDSucursal FROM ROLTRABAJADOR, TRABAJADOR, TRABAJA_EN WHERE CedulaPersona = @ced AND ROLTRABAJADOR.IDTrabajador = TRABAJADOR.ID AND TRABAJA_EN.IDTrabajador = TRABAJADOR.ID AND TRABAJADOR.Estado = 1" ;
        public const string INSERTPERSONA = "INSERT INTO PERSONA (Cedula, Nombre, Apellido1, Apellido2, FechaNac, Sexo) VALUES (@ced, @nom, @ap1, @ap2, @fec, @sexo);";
        public const string INSERTUSUARIO = "INSERT INTO USUARIO (Usuario, Contrasena, CedulaPersona, Trabajador) VALUES (@user, @pw, @ced, @trab);";
        public const string INSERTROL = "INSERT INTO ROL (Nombre, Descripcion)  VALUES (@nomR, @desR);";
        public const string SELECTROL_ASTERISCO = "SELECT * FROM ROL;";
        public const string UPDATEROL = "UPDATE ROL SET Nombre = @nomR, Descripcion = @desR WHERE ID = @idR;";
        public const string DELETEROL = "UPDATE ROL SET Estado = 0 WHERE ID = @idR;";
        public const string INSERTSUCURSAL = "INSERT INTO SUCURSAL(Nombre, Provincia, Canton, Distrito, Telefono) VALUES(@nomS, @prov, @cant, @dis, @tel);";
        public const string SELECTSUCURSAL_ASTERISCO = "SELECT * FROM SUCURSAL;";
        public const string UPDATESUCURSAL = "UPDATE SUCURSAL SET Nombre = @nomS, Provincia = @prov, Canton = @cant, Distrito = @dis, Telefono = @tel WHERE ID = @id;";
        public const string DELETESUCURSAL = "UPDATE SUCURSAL SET Estado = 0 WHERE ID = @id;";
        public const string INSERTTRABAJADOR = "INSERT INTO TRABAJADOR (CedulaPersona, SalarioHora, FechaIngreso) VALUES (@ced, @salary, @fechaIng);";
        public const string SELECTULTIMOTRABAJADOR = "SELECT max(ID) as ID from TRABAJADOR WHERE ESTADO = 1;";
        public const string INSERTTRABAJAEN = "INSERT INTO TRABAJA_EN (IDSucursal, IDTrabajador) VALUES (@id, @idT);";
        public const string INSERTROLTRABAJADOR = "INSERT INTO ROLTRABAJADOR (IDRol, IDTrabajador) VALUES (@idR, @idT);";
        public const string SELECTTRABAJADOR_ASTERISCO = "SELECT * FROM TRABAJADOR";
        public const string SELECTPERSONAS_ASTERISCO = "SELECT * FROM PERSONA";
        public const string SELECTROLTRABAJADOR_ASTERISCO = "SELECT * FROM ROLTRABAJADOR";
        public const string SELECTTRABAJAEN_ASTERISCO = "SELECT * FROM TRABAJA_EN";
        public const string UPDATETRABAJADOR = "UPDATE TRABAJADOR SET SalarioHora = @salary WHERE ID = @id";
        public const string UPDATEPERSONA = " UPDATE PERSONA SET Nombre = @nom, Apellido1 = @ap1, Apellido2 = @ap2 WHERE Cedula = @ced;";
        public const string UPDATEROLTRABAJADOR = "UPDATE ROLTRABAJADOR SET IDRol = @idR WHERE IDTrabajador = @idT;";
        public const string UPDATETRABAJAEN = "UPDATE TRABAJA_EN SET IDSucursal = @id WHERE IDTrabajador = @idT;";
        public const string DELETETRABAJADOR = "UPDATE TRABAJADOR SET Estado = 0 WHERE ID = @idT;";
        public const string DELETEROLTRABAJADOR = "UPDATE ROLTRABAJADOR SET Estado = 0 WHERE IDTrabajador =@idT";
        public const string DELETETRABAJA_EN = "UPDATE TRABAJA_EN SET Estado = 0 WHERE IDTrabajador = @idT";
        public const string INSERTPROVEEDOR = "INSERT INTO PROVEEDOR (Cedula, Nombre, Apellido1, Apellido2)  VALUES (@ced, @nom, @ap1, @ap2);";
        public const string SELECTPROVEEDOR_ASTERISCO = "SELECT * FROM PROVEEDOR WHERE Estado = 1";
        public const string UPDATEPROVEEDOR = "UPDATE Proveedor SET Nombre = @nom, Apellido1 = @ap1, Apellido2 = @ap2 WHERE Cedula = @ced;";
        public const string DELETEPROVEEDOR = "UPDATE Proveedor SET Estado = 0 WHERE Cedula = @ced;";
        public const string INSERTPRODUCTO = "INSERT INTO PRODUCTO (Nombre, Descripcion, PrecioCompra, Impuesto) VALUES (@nom, @desc, @precioCompra, @impuesto);";
        public const string  DELETEPRODUCTO = "UPDATE PRODUCTO SET Estado = 0 WHERE CodigoBarras = @cod";
        public const string DELETEPRODUCTOSUCURSAL = "UPDATE PRODUCTO_SUCURSAL SET Estado = 0 WHERE CodigoBarras = @cod";
        public const string DELETEPROVEIDOPOR = "UPDATE PROVEIDO_POR SET Estado = 0 WHERE CodigoBarras = @cod;";
        public const string SELECTHORAS_TRABAJADOR = "SELECT TRABAJADOR.ID, PERSONA.Nombre, HORAS_SEMANALES.HorasRegulares, HORAS_SEMANALES.HorasExtra, CAST ((HorasRegulares * TRABAJADOR.SalarioHora + HorasExtra * 1.5 * TRABAJADOR.SalarioHora) AS INT) as SALARIO FROM HORAS_SEMANALES,TRABAJADOR, PERSONA WHERE FechaInicio = @fec AND HORAS_SEMANALES.IDTrabajador = TRABAJADOR.ID AND PERSONA.Cedula = TRABAJADOR.CedulaPersona";
        public const string SELECTTRABAJAEN_SUCURSAL = "select * from Trabaja_en, TRABAJADOR where trabaja_en.IDSucursal = @id and TRABAJA_EN.IDTrabajador = TRABAJADOR.ID  and TRABAJADOR.Estado = 1";
        public const string INSERTHORAS = "INSERT INTO HORAS_SEMANALES (FechaInicio, IDTrabajador, HorasRegulares, HorasExtra) VALUES (@fec, @idT, @hReg, @hExt)";
        public const string SELECTPRODUCTOSUCURSAL_IDSUCURSAL = "SELECT PRODUCTO.CodigoBarras as CodigoBarras, PRODUCTO.Nombre, PRODUCTO.PrecioCompra, PRODUCTO_SUCURSAL.PrecioVenta, PRODUCTO.Impuesto, PRODUCTO_SUCURSAL.Descuento FROM PRODUCTO_SUCURSAL, PRODUCTO WHERE IDSucursal = @id AND PRODUCTO.CodigoBarras = PRODUCTO_SUCURSAL.CodigoBarras";
        public const string INSERTPRODUCTOSUCURSAL_IDSUCURSAL = "INSERT INTO PRODUCTO_SUCURSAL (CodigoBarras, IDSucursal, Cantidad, Descuento, PrecioVenta) VALUES (@cod, @id, @cant, @des, @precioVenta)";
        public const string INSERTVENTA = "INSERT INTO VENTA (IDTrabajador, IDSucursal) VALUES (@idT, @id);";
        public const string UPDATEPRODUCTOSUCURSAL = "UPDATE PRODUCTO_SUCURSAL SET Cantidad = Cantidad - @cant WHERE CodigoBarras = @cod AND IDSucursal = @id";
        public const string INSERTVENDIDO = "INSERT INTO VENDIDO(IDVenta, CodigoProducto, Cantidad) VALUES(@idV, @cod, @cant);";
        public const string SELECTULTIMAVENTA = "SELECT max(ID) as ID from VENTA;";
        public const string LISTADOPRODUCTOSTOTALES = "SELECT SUM(Cantidad) as Cantidad, PRODUCTO.Nombre, PRODUCTO.PrecioCompra FROM PRODUCTO_SUCURSAL, PRODUCTO WHERE PRODUCTO_SUCURSAL.CodigoBarras = PRODUCTO.CodigoBarras AND PRODUCTO.Estado = 1 GROUP BY PRODUCTO.PrecioCompra, PRODUCTO.Nombre";
        public const string LISTADOGASTOS = "SELECT COMPRA.FechaReal, PROVEEDOR.Nombre, COMPRA.Descripcion, (COMPRADO.Cantidad * PRODUCTO.PrecioCompra) as Monto FROM COMPRA, COMPRADO, PROVEEDOR, PRODUCTO WHERE COMPRA.CedProveedor = PROVEEDOR.Cedula AND COMPRA.Estado = 1 AND  COMPRADO.IDCompra = COMPRA.ID AND PRODUCTO.CodigoBarras = COMPRADO.CodigoProducto  AND COMPRA.IDSucursal = @id AND COMPRA.FechaReal >= @fecha1 AND COMPRA.FechaReal <= @fecha2 ORDER BY COMPRA.FechaReal";
        public const string LISTADOGASTOSSINSUCURSAL = "SELECT COMPRA.FechaReal, PROVEEDOR.Nombre, COMPRA.Descripcion, (COMPRADO.Cantidad * PRODUCTO.PrecioCompra) as Monto FROM COMPRA, COMPRADO, PROVEEDOR, PRODUCTO WHERE COMPRA.CedProveedor = PROVEEDOR.Cedula AND COMPRA.Estado = 1 AND  COMPRADO.IDCompra = COMPRA.ID AND PRODUCTO.CodigoBarras = COMPRADO.CodigoProducto AND PRODUCTO.Estado = 1 AND COMPRA.FechaReal >= @fecha1 AND COMPRA.FechaReal <= @fecha2 ORDER BY COMPRA.FechaReal";
        public const string LISTADOSUCURSAL = "SELECT PRODUCTO_SUCURSAL.Cantidad, PRODUCTO.Nombre, PRODUCTO.Descripcion, (PRODUCTO_SUCURSAL.PrecioVenta + PRODUCTO.PrecioCompra) as Monto FROM PRODUCTO, PRODUCTO_SUCURSAL WHERE PRODUCTO_SUCURSAL.CodigoBarras = PRODUCTO.CodigoBarras AND PRODUCTO_SUCURSAL.IDSucursal = @id AND PRODUCTO.Estado = 1;";
        public const string SELECTPRODUCTOS_ASTERISCO = "SELECT * FROM PRODUCTO WHERE Estado = 1";
        public const string INSERTPROVEIDO_POR = "INSERT INTO PROVEIDO_POR (CodigoBarras, CedProveedor) VALUES (@cod, @ced);";
        public const string SELECTPROVEIDO_POR = "SELECT PRODUCTO.CodigoBarras, PRODUCTO.Nombre, PRODUCTO.PrecioCompra FROM PRODUCTO, PROVEIDO_POR WHERE PRODUCTO.CodigoBarras = PROVEIDO_POR.CodigoBarras AND PRODUCTO.Estado = 1 AND PROVEIDO_POR.CedProveedor = @ced";
        public const string INSERTCOMPRA = "INSERT INTO COMPRA (Descripcion, FechaRegistro, FechaReal, Foto, IDSucursal, CedProveedor) VALUES (@desc, @fecha1, @fecha2, @foto, @id, @ced);";
        public const string SELECTULTIMACOMPRA = "SELECT MAX(ID) as ID FROM COMPRA WHERE Estado = 1;";
        public const string INSERTCOMPRADO = "INSERT INTO COMPRADO (CodigoProducto, IDCompra, Cantidad) VALUES (@cod, @id, @cant)";
        public const string SELECTCOMPRAS_ASTERISCO = "SELECT * FROM COMPRA";
        public const string DELETECOMPRA = "UPDATE COMPRA SET Estado = 0 WHERE ID = @id";
        public const string UPDATECOMPRA = "UPDATE COMPRA SET Descripcion = @desc, FechaReal = @fec WHERE ID = @id";
        public const string UPDATETRABAJADOR_REHIRE = "UPDATE TRABAJADOR SET Estado = 1 WHERE CedulaPersona = @ced";

        /*Parameters */
        public const string PARAM_FOTO = "@foto";
        public const string PARAM_DESCUENTO = "@des";
        public const string PARAM_FECHAMENOR = "@fecha1";
        public const string PARAM_FECHAMAYOR = "@fecha2";
        public const string PARAM_IDVENTA = "idV";
        public const string PARAM_CANTIDAD = "@cant";
        public const string PARAM_CODIGOBARRAS = "@cod";
        public const string PARAM_DESCRIPCION = "@desc";
        public const string PARAM_PRECIOCOMPRA = "@precioCompra";
        public const string PARAM_PRECIOVENTA = "@precioVenta";
        public const string PARAM_IMPUESTO = "@impuesto";
        public const string PARAM_ID_MINUSC = "@id";
        public const string PARAM_USERNAME = "@user";
        public const string PARAM_PASSWORD = "@pw";
        public const string PARAM_CEDULAPERSONA = "@ced";
        public const string PARAM_NOMBREPERSONA = "@nom";
        public const string PARAM_APELLIDO1PERSONA = "@ap1";
        public const string PARAM_APELLIDO2PERSONA = "@ap2";
        public const string PARAM_FECHA = "@fec";
        public const string PARAM_SEXO = "@sexo";
        public const string PARAM_TRABAJA = "@trab";
        public const string PARAM_IDROL = "@idR";
        public const string PARAM_NOMBREROL = "@nomR";
        public const string PARAM_DESCRIROL = "@desR";
        public const string PARAM_NOMBRESUCURSAL = "@nomS";
        public const string PARAM_PROVINCIA = "@prov";
        public const string PARAM_CANTON = "@cant";
        public const string PARAM_DISTRITO = "@dis";
        public const string PARAM_TELEFONO = "@tel";
        public const string PARAM_SALARIO = "@salary";
        public const string PARAM_FECHAINGRESO = "@fechaIng";
        public const string PARAM_IDTRABAJADOR = "@idT";
        public const string PARAM_HORAS_REG = "@hReg";
        public const string PARAM_HORAS_EXT = "@hExt";

        /*SQL Headers */
        public const string HEADER_HORASREG = "HorasRegulares";
        public const string HEADER_HORASEXTRA = "HorasExtra";
        public const string HEADER_FECHAINICIO = "FechaInicio";
        public const string HEADER_CEDULA = "Cedula";
        public const string HEADER_CEDULAPERSONA = "CedulaPersona";
        public const string HEADER_TRABAJADOR = "Trabajador";
        public const string HEADER_IDROL = "IDRol";
        public const string HEADER_NOMBRE = "Nombre";
        public const string HEADER_DESCRIPCION = "Descripcion";
        public const string HEADER_ID = "ID";
        public const string HEADER_ESTADO = "Estado";
        public const string HEADER_ESTADO2 = "Estado2";
        public const string HEADER_PROVINCIA = "Provincia";
        public const string HEADER_CANTON = "Canton";
        public const string HEADER_DISTRITO = "Distrito";
        public const string HEADER_TELEFONO = "Telefono";
        public const string HEADER_SALARIO = "SalarioHora";
        public const string HEADER_FECHAING = "FechaIngreso";
        public const string HEADER_APELLIDO1 = "Apellido1";
        public const string HEADER_APELLIDO2 = "Apellido2";
        public const string HEADER_FECHANAC = "FechaNac";
        public const string HEADER_IDTRAB = "IDTrabajador";
        public const string HEADER_IDSUCURSAL = "IDSucursal";
        public const string HEADER_CODBARRAS = "CodigoBarras";
        public const string HEADER_PRECIOCOMPRA = "PrecioCompra";
        public const string HEADER_PRECIOVENTA = "PrecioVenta";
        public const string HEADER_DESCUENTO = "Descuento";
        public const string HEADER_IMPUESTO = "Impuesto";
        public const string HEADER_CANTIDAD = "Cantidad";
        public const string HEADER_FECHAREAL = "FechaReal";
        public const string HEADER_MONTO = "Monto";
        public const string HEADER_SALARIOTOTAL = "SALARIO";
        public const string HEADER_CEDULAPROV = "CedProveedor";
    }
}